dist: xenial
language: shell
os: linux
services: docker

cache:
  directories:
  - ${HOME}/.custom_cache
before_cache:
  - sudo chown -R ${USER} ${HOME}/.custom_cache

if: tag IS blank

addons:
  sonarcloud:
    organization: "campisano"

jobs:
  include:
    - stage: "Test"
      if: branch != master
      install: skip
      script:
        - build-wrapper-linux-x86-64 --out-dir bw-output ./ci/build.sh
        - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
        - ./ci/build.sh
        - ./ci/test.sh
        - ./ci/coverage.sh
    - stage: "Deliver"
      if: branch = master
      install: skip
      script:
        - ./ci/build.sh
        - ./ci/test.sh
        - ./ci/deliver.sh
        - ./ci/coverage.sh
