dist: xenial
language: shell
os: linux
services: docker

cache:
  directories:
  - ${HOME}/.custom_cache
before_cache:
  - sudo chown -R ${USER} ${HOME}/.custom_cache

if: tag IS blank

jobs:
  include:
    - stage: "Test"
      if: branch != master
      install: skip
      script:
        - ./ci/build.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
        - ./ci/test.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
        - ./ci/coverage.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
        - ./ci/sonar.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
    - stage: "Deliver"
      if: branch = master
      install: skip
      script:
        - ./ci/build.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
        - ./ci/test.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
        - ./ci/deliver.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
        - ./ci/coverage.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
        - ./ci/sonar.sh $(basename "$TRAVIS_BUILD_DIR") "$TRAVIS_BRANCH"
